### ISSUE TITLE
@nativescript-community/texttospeech is not a valid NativeScript plugin. 

### ISSUE THREAD

**Issue by kakha13** [nativescript-community/texttospeech#24]
`@nativescript-community/texttospeech `is not a valid NativeScript plugin. Verify that the plugin package.json file contains a nativescript key and try again.

What can i do?

**Comment by bradmartin** [comment]
Seems to be working correctly now. Might have been a temporary issue or not published at the time you attempted to install it.

**Comment by MPerezMateo** [comment]
I am having the same issue. Note that I am not using ns 7.0, but 6.5 instead.

**Comment by aabeling** [comment]
Neither does it work for me. I am using ns 6.5.0, too.
Any old release working with 6.5.0?

**Comment by Klunk75** [comment]
Hi, same issue here (I'm using NS7)...

**Comment by kakha13** [comment]
"nativescript-texttospeech": "^2.0.3", working great

**Comment by darkyelox** [comment]
You can install and use the plugin through NPM, it may work.

`npm install  @nativescript-community/texttospeech --save`

The package problem should be fixed in near future for us to use NS command.
