### ISSUE TITLE
speackRate param doesn't work on iOS

### ISSUE THREAD

**Issue by Bezlepkin** [nativescript-community/texttospeech#29]
https://github.com/nativescript-community/texttospeech/blob/9cf631e7991ab5c995cbfe5d2ae265378221c454/src/texttospeech.ios.ts#L76

Because of these three lines, the setting of the reading speed does not work.

In general, their logic is not clear :) 
In all cases, the value will be 1.

**Comment by farfromrefug** [comment]
@Bezlepkin i dont understand what you mean. The logic seems fine to me.

**Comment by Bezlepkin** [comment]
I\m sorry, i didn't notice AVSpeechUtteranceMinimumSpeechRate :)
